/**
 * generated by Xtext 2.21.0
 */
package workflow.workflowDSL.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import workflow.workflowDSL.ParameterValueTypes;
import workflow.workflowDSL.WorkflowDSLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Parameter Value Types</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ParameterValueTypesImpl extends MinimalEObjectImpl.Container implements ParameterValueTypes
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParameterValueTypesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WorkflowDSLPackage.Literals.PARAMETER_VALUE_TYPES;
  }

} //ParameterValueTypesImpl
