/**
 * generated by Xtext 2.21.0
 */
package workflow.workflowDSL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import workflow.workflowDSL.MessageQueue;
import workflow.workflowDSL.SinkStep;
import workflow.workflowDSL.WorkflowDSLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sink Step</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link workflow.workflowDSL.impl.SinkStepImpl#getReadFrom <em>Read From</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SinkStepImpl extends StepImpl implements SinkStep
{
  /**
   * The cached value of the '{@link #getReadFrom() <em>Read From</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReadFrom()
   * @generated
   * @ordered
   */
  protected MessageQueue readFrom;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SinkStepImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WorkflowDSLPackage.Literals.SINK_STEP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MessageQueue getReadFrom()
  {
    return readFrom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReadFrom(MessageQueue newReadFrom, NotificationChain msgs)
  {
    MessageQueue oldReadFrom = readFrom;
    readFrom = newReadFrom;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WorkflowDSLPackage.SINK_STEP__READ_FROM, oldReadFrom, newReadFrom);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReadFrom(MessageQueue newReadFrom)
  {
    if (newReadFrom != readFrom)
    {
      NotificationChain msgs = null;
      if (readFrom != null)
        msgs = ((InternalEObject)readFrom).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WorkflowDSLPackage.SINK_STEP__READ_FROM, null, msgs);
      if (newReadFrom != null)
        msgs = ((InternalEObject)newReadFrom).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WorkflowDSLPackage.SINK_STEP__READ_FROM, null, msgs);
      msgs = basicSetReadFrom(newReadFrom, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WorkflowDSLPackage.SINK_STEP__READ_FROM, newReadFrom, newReadFrom));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case WorkflowDSLPackage.SINK_STEP__READ_FROM:
        return basicSetReadFrom(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WorkflowDSLPackage.SINK_STEP__READ_FROM:
        return getReadFrom();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WorkflowDSLPackage.SINK_STEP__READ_FROM:
        setReadFrom((MessageQueue)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WorkflowDSLPackage.SINK_STEP__READ_FROM:
        setReadFrom((MessageQueue)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WorkflowDSLPackage.SINK_STEP__READ_FROM:
        return readFrom != null;
    }
    return super.eIsSet(featureID);
  }

} //SinkStepImpl
