/*
 * generated by Xtext 2.27.0
 */
package se.kth.datacloud.dsl.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DataCloudDSLUiModule extends AbstractDataCloudDSLUiModule {

	public DataCloudDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
