/*
 * generated by Xtext 2.27.0
 */
package se.kth.datacloud.dsl.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DataCloudDSLStandaloneSetup extends DataCloudDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new DataCloudDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
