<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="wfDsl" nsURI="http://www.example.org/wfDsl" nsPrefix="wfDsl">
  <eClassifiers xsi:type="ecore:EClass" name="Pipeline" eSuperTypes="#//PipelineTemplate"/>
  <eClassifiers xsi:type="ecore:EClass" name="PipelineTemplate" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractstep" lowerBound="1"
        upperBound="-1" eType="#//AbstractStep" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="communicationMedium" eType="#//CommunicationMedium"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentParameters"
        upperBound="-1" eType="#//EnvironmentParameters/EnvironmentParameters" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubPipeline" eSuperTypes="#//PipelineTemplate"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractStep" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1"
        eType="#//Trigger/Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" unique="false"
        upperBound="-1" eType="#//AbstractStep"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlParemeter" lowerBound="1"
        eType="#//ControlParameters/ControlParemeter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionRequirements"
        eType="#//ExecutionRequirements/ExecutionRequirement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceProvider" lowerBound="1"
        upperBound="-1" eType="#//ResourceProvider/ResourceProvider" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentParameters"
        upperBound="-1" eType="#//EnvironmentParameters/EnvironmentParameters" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementation" eType="#//StepImplementation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationMedium">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CommunicationMediumTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StepImplementation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerImplementation" eSuperTypes="#//StepImplementation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CommunicationMediumTypes">
    <eLiterals name="MESSAGE_QUEUE" literal="MESSAGE_QUEUE"/>
    <eLiterals name="DISTRIBUTED_FILE_SYSTEM" value="1" literal="DISTRIBUTED_FILE_SYSTEM"/>
    <eLiterals name="WEB_SERVICE" value="2" literal="WEB_SERVICE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeUnits">
    <eLiterals name="SECOND" literal="SECOND"/>
    <eLiterals name="MINUTE" value="1" literal="MINUTE"/>
    <eLiterals name="HOUR" value="2" literal="HOUR"/>
    <eLiterals name="DAY" value="3" literal="DAY"/>
    <eLiterals name="WEEK" value="4" literal="WEEK"/>
    <eLiterals name="MONTH" value="5" literal="MONTH"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeploymentLayers">
    <eLiterals name="EDGE" value="1"/>
    <eLiterals name="FOG" value="1"/>
    <eLiterals name="CLOUD" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeStep" eSuperTypes="#//AbstractStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="1" upperBound="-1"
        eType="#//AbstractStep" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subpipeline" eType="#//SubPipeline"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StepTemplate" abstract="true" interface="true"
      eSuperTypes="#//AbstractStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataSource" upperBound="-1"
        eType="#//DataSourceParameters/InputDataSource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterOperator" eType="#//LogicalOperatorType"
        defaultValueLiteral="AND"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LogicalOperatorType">
    <eLiterals name="AND"/>
    <eLiterals name="XOR" value="1"/>
    <eLiterals name="OR" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparisonOperatorType">
    <eLiterals name="EQUAL"/>
    <eLiterals name="LESS_THAN" value="1"/>
    <eLiterals name="GREATER_THAN" value="2"/>
    <eLiterals name="NOT_EQAL" value="3"/>
    <eLiterals name="EQUAL_LESS_THAN" value="4"/>
    <eLiterals name="EQUAL_GREATER_THAN" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="AbstractCondition" instanceClassName="AbstractContition"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Step" instanceTypeName="Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataProcesssing" eSuperTypes="#//StepTemplate"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource" eSuperTypes="#//StepTemplate"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataSink" eSuperTypes="#//StepTemplate"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IterationProcessing" instanceTypeName="newDataType8"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DeploymentEnvironment" instanceTypeName="newDataType10"/>
  <eSubpackages name="Trigger" nsURI="http://www.example.org/wfDsl/Trigger" nsPrefix="Trigger">
    <eClassifiers xsi:type="ecore:EClass" name="ScheduleTrigger" eSuperTypes="#//Trigger/Trigger">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Trigger"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalEventTrigger" eSuperTypes="#//Trigger/Trigger"/>
    <eClassifiers xsi:type="ecore:EClass" name="OneTimeTrigger" eSuperTypes="#//Trigger/Trigger">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CronSchedule" eSuperTypes="#//Trigger/ScheduleTrigger">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cron" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntervalSchedule" eSuperTypes="#//Trigger/ScheduleTrigger">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="#//TimeUnits"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Polling" eSuperTypes="#//Trigger/Trigger">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="#//AbstractCondition"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfRetries" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PollDatabase" eSuperTypes="#//Trigger/Polling">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="credential" eType="#//Trigger/DatabaseCredentials"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="queryScript" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PollMessageQueue" eSuperTypes="#//Trigger/Polling">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="credential" eType="#//Trigger/MessageQueueCredentials"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumerQueueName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PollWebService" eSuperTypes="#//Trigger/Polling">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="credential" eType="#//Trigger/WebApiCredentials"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="DatabaseCredentials" instanceTypeName="newDataType1"/>
    <eClassifiers xsi:type="ecore:EDataType" name="WebApiCredentials" instanceTypeName="newDataType2"/>
    <eClassifiers xsi:type="ecore:EDataType" name="MessageQueueCredentials" instanceTypeName="newDataType3"/>
  </eSubpackages>
  <eSubpackages name="ExecutionRequirements" nsURI="http://www.example.org/wfDsl/ExecutionRequirements"
      nsPrefix="ExecutionRequirements">
    <eClassifiers xsi:type="ecore:EClass" name="ExecutionRequirement" eSuperTypes="#//Parameter">
      <eStructuralFeatures xsi:type="ecore:EReference" name="hardRequirements" eType="#//ExecutionRequirements/HardRequirements"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="softRequirements" eType="#//ExecutionRequirements/SoftRequirements"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HardRequirements" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="osOrImageReq" eType="#//ExecutionRequirements/OSOrImageRequirements"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scaleRequirements" eType="#//ExecutionRequirements/ScaleRequirements"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hardwareRequirement"
          eType="#//ExecutionRequirements/HardwareRequirements" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="securityRequirements"
          eType="#//ExecutionRequirements/SecurityRequirement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sloRequirements" eType="#//ExecutionRequirements/ServiceLevelObjective"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SoftRequirements" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Metric">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueDirection" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isVariable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OptimizationRequirements" eSuperTypes="#//ExecutionRequirements/SoftRequirements">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="optimisationFunction"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="MINIMIZE"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="metric" lowerBound="1"
          eType="#//ExecutionRequirements/Metric"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HardwareRequirements" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="networkRequirements"
          eType="#//ExecutionRequirements/NetworkRequirements" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qualitativeRequirements"
          eType="#//ExecutionRequirements/QualitativeHardwareRequirements" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="quantitativeRequirements"
          eType="#//ExecutionRequirements/QuantitativeHardwareRequirements" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServiceLevelCondition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparisonOperator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="GREATER_THAN"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HorizontalScaleRequirements">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minInstance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxInstance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OSRequirements" eSuperTypes="#//ExecutionRequirements/OSOrImageRequirements">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="osType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="is64os" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ServiceLevelObjective">
      <eStructuralFeatures xsi:type="ecore:EReference" name="customServiceLevel" eType="#//ExecutionRequirements/ServiceLevelCondition"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SecurityRequirement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QuantitativeHardwareRequirements">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCpu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCpu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minRamMiB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxRamMiB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minStorageMB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxStorageMB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpuFrequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpuNumberOfCores" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gpuAvailability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ScaleRequirements" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="verticalScaleReq" eType="#//ExecutionRequirements/VerticalScaleRequirements"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="horizontalScaleReq" eType="#//ExecutionRequirements/HorizontalScaleRequirements"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OSOrImageRequirements" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ImageRequirements" eSuperTypes="#//ExecutionRequirements/OSOrImageRequirements">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VerticalScaleRequirements">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCpu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCpu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minRamMiB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxRamMiB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCores" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCores" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minStorageMB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxStorageMB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QualitativeHardwareRequirements">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minBenchmark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxBenchmark" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpuArchitecture" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gpuArchitecture" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NetworkRequirements">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minBandwidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxBandwidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minLatency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLatency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="ControlParameters" nsURI="http://www.example.org/wfDsl/ControlParameters"
      nsPrefix="ControlParameters">
    <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//ControlParameters/AbstractCondition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparatorOperator" eType="#//ComparisonOperatorType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceProcessingScriptName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="None"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractCondition" instanceClassName="AbstractCondition"
        abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeCondition" eSuperTypes="#//ControlParameters/AbstractCondition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
          eType="#//ControlParameters/AbstractCondition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//LogicalOperatorType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PreCondition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="conditionStepList" lowerBound="1"
          upperBound="-1" eType="#//ControlParameters/ConditionStepPair" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//LogicalOperatorType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PostCondition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="conditionStepList" lowerBound="1"
          upperBound="-1" eType="#//ControlParameters/ConditionStepPair" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConditionStepPair">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="#//AbstractCondition"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="step" eType="#//Step"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WhileLooop" eSuperTypes="#//ControlParameters/LoopParameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="#//AbstractCondition"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="atLeastOnce" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ForLoop" eSuperTypes="#//ControlParameters/LoopParameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="from" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="to" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//ControlParameters/OperatorType"
          defaultValueLiteral="INCREMENT"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoopParameter"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConditionParameter">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pre" eType="#//ControlParameters/PreCondition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="post" eType="#//ControlParameters/PostCondition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="OperatorType">
      <eLiterals name="INCREMENT"/>
      <eLiterals name="DECREMENT" value="1"/>
      <eLiterals name="DIVISION" value="2"/>
      <eLiterals name="MULTIPLY" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ControlParemeter" eSuperTypes="#//Parameter">
      <eStructuralFeatures xsi:type="ecore:EReference" name="loop" eType="#//ControlParameters/LoopParameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//ControlParameters/ConditionParameter"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="DataSourceParameters" nsURI="http://www.example.org/wfDsl/DataSourceParameters"
      nsPrefix="DataSourceParameters">
    <eClassifiers xsi:type="ecore:EClass" name="InputDataSource" eSuperTypes="#//Parameter">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//DataSourceParameters/ParameterValueTypes"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="datasourcecredentials"
          lowerBound="1" eType="#//DataSourceParameters/DataSourceCredentials" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterValueTypes">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataSourceCredentials"/>
    <eClassifiers xsi:type="ecore:EClass" name="BlockStorage" eSuperTypes="#//DataSourceParameters/InputDataSource"/>
    <eClassifiers xsi:type="ecore:EClass" name="Database" eSuperTypes="#//DataSourceParameters/InputDataSource"/>
    <eClassifiers xsi:type="ecore:EClass" name="MessageQueue" eSuperTypes="#//DataSourceParameters/InputDataSource"/>
    <eClassifiers xsi:type="ecore:EClass" name="WebApi" eSuperTypes="#//DataSourceParameters/InputDataSource"/>
    <eClassifiers xsi:type="ecore:EClass" name="WebApiCredentials" eSuperTypes="#//DataSourceParameters/DataSourceCredentials">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MessageQueueCredentials" eSuperTypes="#//DataSourceParameters/DataSourceCredentials"/>
    <eClassifiers xsi:type="ecore:EClass" name="DatabaseCredentials" eSuperTypes="#//DataSourceParameters/DataSourceCredentials"/>
    <eClassifiers xsi:type="ecore:EClass" name="BlockStorageCredential" eSuperTypes="#//DataSourceParameters/DataSourceCredentials"/>
    <eClassifiers xsi:type="ecore:EClass" name="FTP" eSuperTypes="#//DataSourceParameters/BlockStorage"/>
    <eClassifiers xsi:type="ecore:EClass" name="SFTP" eSuperTypes="#//DataSourceParameters/BlockStorage"/>
  </eSubpackages>
  <eSubpackages name="ResourceProvider" nsURI="http://www.example.org/wfDsl/ResourceProvider"
      nsPrefix="ResourceProvider">
    <eClassifiers xsi:type="ecore:EClass" name="ResourceProvider" eSuperTypes="#//Parameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="providerName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mappingLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CloudProvider" eSuperTypes="#//ResourceProvider/ResourceProvider"/>
    <eClassifiers xsi:type="ecore:EClass" name="FogProvider" eSuperTypes="#//ResourceProvider/ResourceProvider"/>
    <eClassifiers xsi:type="ecore:EClass" name="EdgeProvider" eSuperTypes="#//ResourceProvider/ResourceProvider"/>
  </eSubpackages>
  <eSubpackages name="EnvironmentParameters" nsURI="http://www.example.org/wfDsl/EnvironmentParameters"
      nsPrefix="EnvironmentParameters">
    <eClassifiers xsi:type="ecore:EClass" name="EnvironmentParameters" eSuperTypes="#//Parameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
