/*
 * generated by Xtext 2.21.0
 */
package workflow.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import workflow.ui.internal.WorkflowActivator;

public class WorkflowDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return WorkflowActivator.getInstance().getInjector("workflow.WorkflowDSL");
	}

}
