/*
 * generated by Xtext 2.21.0
 */
package workflow.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import workflow.ui.internal.WorkflowActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WorkflowDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(WorkflowActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		WorkflowActivator activator = WorkflowActivator.getInstance();
		return activator != null ? activator.getInjector(WorkflowActivator.WORKFLOW_WORKFLOWDSL) : null;
	}

}
