/*
 * generated by Xtext 2.21.0
 */
package workflow.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWorkflowDSLScopeProvider extends DelegatingScopeProvider {
}
