/*
 * generated by Xtext 2.21.0
 */
package workflow.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractWorkflowDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(workflow.workflowDSL.WorkflowDSLPackage.eINSTANCE);
		return result;
	}
}
