/*
 * generated by Xtext 2.21.0
 */
package workflow.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WorkflowDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("workflow/parser/antlr/internal/InternalWorkflowDSL.tokens");
	}
}
