/*
 * generated by Xtext 2.21.0
 */
package workflow.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import workflow.parser.antlr.internal.InternalWorkflowDSLParser;
import workflow.services.WorkflowDSLGrammarAccess;

public class WorkflowDSLParser extends AbstractAntlrParser {

	@Inject
	private WorkflowDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalWorkflowDSLParser createParser(XtextTokenStream stream) {
		return new InternalWorkflowDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "WFModel";
	}

	public WorkflowDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(WorkflowDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
