/*
 * generated by Xtext 2.27.0
 */
package se.kth.datacloud.dsl.xtext.ide;


/**
 * Use this class to register ide components.
 */
public class DataCloudDSLIdeModule extends AbstractDataCloudDSLIdeModule {
}
