/*
 * generated by Xtext 2.21.0
 */
package workflow;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class WorkflowDSLStandaloneSetup extends WorkflowDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new WorkflowDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
