/**
 * generated by Xtext 2.21.0
 */
package workflow.workflowDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bool Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link workflow.workflowDSL.BoolType#isValue <em>Value</em>}</li>
 * </ul>
 *
 * @see workflow.workflowDSL.WorkflowDSLPackage#getBoolType()
 * @model
 * @generated
 */
public interface BoolType extends ParameterValueTypes
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(boolean)
   * @see workflow.workflowDSL.WorkflowDSLPackage#getBoolType_Value()
   * @model
   * @generated
   */
  boolean isValue();

  /**
   * Sets the value of the '{@link workflow.workflowDSL.BoolType#isValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #isValue()
   * @generated
   */
  void setValue(boolean value);

} // BoolType
