/**
 * generated by Xtext 2.21.0
 */
package workflow.workflowDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Intermediate Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link workflow.workflowDSL.IntermediateStep#getReadFrom <em>Read From</em>}</li>
 *   <li>{@link workflow.workflowDSL.IntermediateStep#getWriteTo <em>Write To</em>}</li>
 * </ul>
 *
 * @see workflow.workflowDSL.WorkflowDSLPackage#getIntermediateStep()
 * @model
 * @generated
 */
public interface IntermediateStep extends Step
{
  /**
   * Returns the value of the '<em><b>Read From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Read From</em>' containment reference.
   * @see #setReadFrom(MessageQueue)
   * @see workflow.workflowDSL.WorkflowDSLPackage#getIntermediateStep_ReadFrom()
   * @model containment="true"
   * @generated
   */
  MessageQueue getReadFrom();

  /**
   * Sets the value of the '{@link workflow.workflowDSL.IntermediateStep#getReadFrom <em>Read From</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Read From</em>' containment reference.
   * @see #getReadFrom()
   * @generated
   */
  void setReadFrom(MessageQueue value);

  /**
   * Returns the value of the '<em><b>Write To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Write To</em>' containment reference.
   * @see #setWriteTo(MessageQueue)
   * @see workflow.workflowDSL.WorkflowDSLPackage#getIntermediateStep_WriteTo()
   * @model containment="true"
   * @generated
   */
  MessageQueue getWriteTo();

  /**
   * Sets the value of the '{@link workflow.workflowDSL.IntermediateStep#getWriteTo <em>Write To</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Write To</em>' containment reference.
   * @see #getWriteTo()
   * @generated
   */
  void setWriteTo(MessageQueue value);

} // IntermediateStep
