/**
 * generated by Xtext 2.21.0
 */
package workflow.workflowDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Message Queue</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link workflow.workflowDSL.MessageQueue#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see workflow.workflowDSL.WorkflowDSLPackage#getMessageQueue()
 * @model
 * @generated
 */
public interface MessageQueue extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see workflow.workflowDSL.WorkflowDSLPackage#getMessageQueue_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link workflow.workflowDSL.MessageQueue#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // MessageQueue
