/**
 * generated by Xtext 2.21.0
 */
package workflow.workflowDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter Value Types</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see workflow.workflowDSL.WorkflowDSLPackage#getParameterValueTypes()
 * @model
 * @generated
 */
public interface ParameterValueTypes extends EObject
{
} // ParameterValueTypes
