/**
 * generated by Xtext 2.21.0
 */
package workflow.workflowDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sink Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link workflow.workflowDSL.SinkStep#getReadFrom <em>Read From</em>}</li>
 * </ul>
 *
 * @see workflow.workflowDSL.WorkflowDSLPackage#getSinkStep()
 * @model
 * @generated
 */
public interface SinkStep extends Step
{
  /**
   * Returns the value of the '<em><b>Read From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Read From</em>' containment reference.
   * @see #setReadFrom(MessageQueue)
   * @see workflow.workflowDSL.WorkflowDSLPackage#getSinkStep_ReadFrom()
   * @model containment="true"
   * @generated
   */
  MessageQueue getReadFrom();

  /**
   * Sets the value of the '{@link workflow.workflowDSL.SinkStep#getReadFrom <em>Read From</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Read From</em>' containment reference.
   * @see #getReadFrom()
   * @generated
   */
  void setReadFrom(MessageQueue value);

} // SinkStep
