/**
 * generated by Xtext 2.21.0
 */
package workflow.workflowDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Source Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link workflow.workflowDSL.SourceStep#getWriteTo <em>Write To</em>}</li>
 * </ul>
 *
 * @see workflow.workflowDSL.WorkflowDSLPackage#getSourceStep()
 * @model
 * @generated
 */
public interface SourceStep extends Step
{
  /**
   * Returns the value of the '<em><b>Write To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Write To</em>' containment reference.
   * @see #setWriteTo(MessageQueue)
   * @see workflow.workflowDSL.WorkflowDSLPackage#getSourceStep_WriteTo()
   * @model containment="true"
   * @generated
   */
  MessageQueue getWriteTo();

  /**
   * Sets the value of the '{@link workflow.workflowDSL.SourceStep#getWriteTo <em>Write To</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Write To</em>' containment reference.
   * @see #getWriteTo()
   * @generated
   */
  void setWriteTo(MessageQueue value);

} // SourceStep
