/**
 * generated by Xtext 2.21.0
 */
package workflow.workflowDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link workflow.workflowDSL.Step#getName <em>Name</em>}</li>
 *   <li>{@link workflow.workflowDSL.Step#isRecurring <em>Recurring</em>}</li>
 *   <li>{@link workflow.workflowDSL.Step#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see workflow.workflowDSL.WorkflowDSLPackage#getStep()
 * @model
 * @generated
 */
public interface Step extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see workflow.workflowDSL.WorkflowDSLPackage#getStep_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link workflow.workflowDSL.Step#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Recurring</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Recurring</em>' attribute.
   * @see #setRecurring(boolean)
   * @see workflow.workflowDSL.WorkflowDSLPackage#getStep_Recurring()
   * @model
   * @generated
   */
  boolean isRecurring();

  /**
   * Sets the value of the '{@link workflow.workflowDSL.Step#isRecurring <em>Recurring</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Recurring</em>' attribute.
   * @see #isRecurring()
   * @generated
   */
  void setRecurring(boolean value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link workflow.workflowDSL.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see workflow.workflowDSL.WorkflowDSLPackage#getStep_Params()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParams();

} // Step
