/**
 * generated by Xtext 2.21.0
 */
package workflow.workflowDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link workflow.workflowDSL.StringType#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see workflow.workflowDSL.WorkflowDSLPackage#getStringType()
 * @model
 * @generated
 */
public interface StringType extends ParameterValueTypes
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see workflow.workflowDSL.WorkflowDSLPackage#getStringType_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link workflow.workflowDSL.StringType#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // StringType
