/**
 * generated by Xtext 2.21.0
 */
package workflow.workflowDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>WF Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link workflow.workflowDSL.WFModel#getWorkflow <em>Workflow</em>}</li>
 * </ul>
 *
 * @see workflow.workflowDSL.WorkflowDSLPackage#getWFModel()
 * @model
 * @generated
 */
public interface WFModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Workflow</b></em>' containment reference list.
   * The list contents are of type {@link workflow.workflowDSL.Workflow}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Workflow</em>' containment reference list.
   * @see workflow.workflowDSL.WorkflowDSLPackage#getWFModel_Workflow()
   * @model containment="true"
   * @generated
   */
  EList<Workflow> getWorkflow();

} // WFModel
